# Linear Algebra

- 标量
- 向量
    - 点乘
    - 正交（点乘=0）
- 矩阵
    - 乘法（空间扭曲）
    - 对称（总有特征向量）与反对称
    - 正定矩阵
    - 正交矩阵
    - 置换矩阵
    - 特征向量与特征值

In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)

tensor([5.])
tensor([1.])
tensor([6.])
tensor([1.5000])
tensor([9.])


In [2]:
matrix = torch.arange(20).reshape(5, 4)
print(matrix)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


In [3]:
print(matrix.T)

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [4]:
matrix_symmetry = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(matrix_symmetry)
print(matrix_symmetry == matrix_symmetry.T)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [5]:
X = torch.arange(60, dtype=torch.float32).reshape(3, 4, 5)
# 3 elements
# 4 rows
# 5 columns
print(X)

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]],

        [[40., 41., 42., 43., 44.],
         [45., 46., 47., 48., 49.],
         [50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59.]]])


In [6]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
# allocate new space
B = A.clone()
print(A)
print(B)
print(A + B)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])


In [7]:
# element-product
print(A * B)

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [8]:
print(X + 2)

tensor([[[ 2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16.],
         [17., 18., 19., 20., 21.]],

        [[22., 23., 24., 25., 26.],
         [27., 28., 29., 30., 31.],
         [32., 33., 34., 35., 36.],
         [37., 38., 39., 40., 41.]],

        [[42., 43., 44., 45., 46.],
         [47., 48., 49., 50., 51.],
         [52., 53., 54., 55., 56.],
         [57., 58., 59., 60., 61.]]])


In [9]:
print(X.sum())
print(X.shape)

tensor(1770.)
torch.Size([3, 4, 5])


In [10]:
X_sum_0 = X.sum(axis=0)
print(X_sum_0)
print(X_sum_0.shape)

tensor([[ 60.,  63.,  66.,  69.,  72.],
        [ 75.,  78.,  81.,  84.,  87.],
        [ 90.,  93.,  96.,  99., 102.],
        [105., 108., 111., 114., 117.]])
torch.Size([4, 5])


In [11]:
X_sum_1 = X.sum(axis=1)
print(X_sum_1)
print(X_sum_1.shape)

tensor([[ 30.,  34.,  38.,  42.,  46.],
        [110., 114., 118., 122., 126.],
        [190., 194., 198., 202., 206.]])
torch.Size([3, 5])


In [12]:
X_sum_2 = X.sum(axis=2)
print(X_sum_2)
print(X_sum_2.shape)

tensor([[ 10.,  35.,  60.,  85.],
        [110., 135., 160., 185.],
        [210., 235., 260., 285.]])
torch.Size([3, 4])


In [13]:
X_sum_01 = X.sum(axis=[0, 1])
print(X_sum_01)
print(X_sum_01.shape)

tensor([330., 342., 354., 366., 378.])
torch.Size([5])


In [14]:
print(X.mean())
print(X.sum() / X.numel())

tensor(29.5000)
tensor(29.5000)


In [15]:
A_sum_1 = A.sum(axis=1, keepdims=True)
print(A_sum_1)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


In [16]:
print(A / A_sum_1)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])


In [17]:
print(A.cumsum(axis=0))
# 累加

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [20]:
a = torch.ones(4, dtype=torch.float32)
b = torch.tensor([0., 1, 2, 3])
print(a)
print(b)
# product by element
# sum all results
# scalar quantity
print(torch.dot(a, b))
print(torch.sum(a * b))

tensor([1., 1., 1., 1.])
tensor([0., 1., 2., 3.])
tensor(6.)
tensor(6.)


In [24]:
print(A.shape)
print(b.shape)
# matrix and vector multiplication
print(torch.mv(A, b))

torch.Size([5, 4])
torch.Size([4])
tensor([ 14.,  38.,  62.,  86., 110.])


In [25]:
B = torch.ones(4, 3)
# matrix and matrix multiplication
print(torch.mm(A, B))

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [27]:
vector = torch.tensor([3., -4])
# L2 norm
print(torch.norm(vector))
# L1 norm
print(torch.abs(vector).sum())

tensor(5.)
tensor(7.)


In [28]:
# frobenius norm
# matrix -> vector -> L2
print(torch.norm(torch.ones(4, 9)))

tensor(6.)
