- 0 dimension: single value
- 1 dimension: vector
- 2 dimension: matrix
- 3 dimension: a RGB image
- 4 dimension: a set of RGB images
- 5 dimension: video (batch_size, time_node, width, height, channels)

In [4]:
import sys

print(sys.version)

3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)]


In [5]:
import numpy as np

rows, cols = 7, 7
matrix = [[(i * rows + j) for j in range(cols)] for i in range(rows)]

In [6]:
for row in matrix:
    print(row)

[0, 1, 2, 3, 4, 5, 6]
[7, 8, 9, 10, 11, 12, 13]
[14, 15, 16, 17, 18, 19, 20]
[21, 22, 23, 24, 25, 26, 27]
[28, 29, 30, 31, 32, 33, 34]
[35, 36, 37, 38, 39, 40, 41]
[42, 43, 44, 45, 46, 47, 48]


In [57]:
print(matrix[1][2])
print(matrix[1])
print(matrix[:3])
print(matrix[5:])
print(matrix[3:5])
# matrix = matrix[:3] + matrix[3:5] + matrix[5:]

9
[7, 8, 9, 10, 11, 12, 13]
[[0, 1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12, 13], [14, 15, 16, 17, 18, 19, 20]]
[[35, 36, 37, 38, 39, 40, 41], [42, 43, 44, 45, 46, 47, 48]]
[[21, 22, 23, 24, 25, 26, 27], [28, 29, 30, 31, 32, 33, 34]]


In [3]:
import torch

In [38]:
x = torch.arange(12)
print(x.shape)
# number of elements
print(x.numel())

torch.Size([12])
12


In [39]:
x_reshape = x.reshape(3, 4)
print(x_reshape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [41]:
torch.zeros(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [42]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [72]:
x_matrix = torch.tensor(matrix)
print(x_matrix)

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48]])


In [46]:
print(x_matrix.shape)

torch.Size([7, 7])


In [48]:
a = torch.tensor([1.0, 2.0, 4.0, 8.0])
b = torch.tensor([2, 2, 2, 2])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])


In [49]:
torch.exp(a)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [52]:
a = torch.arange(12, dtype=torch.float32).reshape(3, 4)
b = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((a, b), dim=0))
print(torch.cat((a, b), dim=1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [53]:
print(a == b)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


In [54]:
print(a.sum(), b.sum())

tensor(66.) tensor(30.)


In [55]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
print(a)
print(b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [56]:
print(a + b)
# a.shape(), a.shape() = (3, 2), (3, 2)

tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [74]:
print(x_matrix[::3, ::2])
print(x_matrix[::3, ::4])
x_matrix[0:2, :] = 12
print(x_matrix)

tensor([[12, 12, 12, 12],
        [21, 23, 25, 27],
        [42, 44, 46, 48]])
tensor([[12, 12],
        [21, 25],
        [42, 46]])
tensor([[12, 12, 12, 12, 12, 12, 12],
        [12, 12, 12, 12, 12, 12, 12],
        [14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47, 48]])


In [68]:
before_pointer = id(x_matrix)
x_matrix = x_matrix + torch.arange(49).reshape(x_matrix.shape)
print(before_pointer)
print(id(x_matrix))
print(before_pointer == id(x_matrix))

1613732415024
1613733444080
False


In [69]:
x_copy = torch.zeros_like(x_matrix)
print(id(x_copy))
x_copy[:] = x_matrix - torch.arange(49).reshape(x_matrix.shape)
print(id(x_copy))

1613733444480
1613733444480


In [76]:
print(type(a.numpy()), type(b))
c = torch.tensor([7.0])
print(c, c.item(), float(c), int(c))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([7.]) 7.0 7.0 7


In [79]:
import os

os.makedirs('data', exist_ok=True)
data_file = os.path.join('data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [81]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [82]:
data # html

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [84]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)
print(outputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64


C:\Users\87236\AppData\Local\Temp\ipykernel_1484\267443668.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [90]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [91]:
X, y = torch.tensor(inputs.values, dtype=torch.float32), torch.tensor(outputs.values)
print(X, "\n", y)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]]) 
 tensor([127500, 106000, 178100, 140000])
