# Linear Algebra

- 标量
- 向量
    - 点乘
    - 正交（点乘=0）
- 矩阵
    - 乘法（空间扭曲）
    - 对称（总有特征向量）与反对称
    - 正定矩阵
    - 正交矩阵
    - 置换矩阵
    - 特征向量与特征值

In [8]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)

tensor([5.])
tensor([1.])
tensor([6.])
tensor([1.5000])
tensor([9.])


In [11]:
matrix = torch.arange(20).reshape(5, 4)
print(matrix)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


In [12]:
print(matrix.T)

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])
